name: sholat_nu_muhamadiyah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+96

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.1
  adhan: ^2.0.0+1
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  google_fonts: ^8.1.0
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  permission_handler: ^12.0.3
  geolocator: ^14.0.2
  http: ^1.2.0
  web: ^1.1.1

  # Local packages
  web_compass:
    path: ./packages/web_compass
  web_ar_camera:
    path: ./packages/web_ar_camera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
