name: web_ar_camera
description: A clean Flutter Web package to display environment-facing camera feeds as a background view for AR overlays.
version: 1.0.0
# publish_to: 'none' # Or remove when ready to publish to pub.dev

environment:
  sdk: ^3.12.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1
